name: demo
channels:
  - defaults
dependencies:
  - freeglut=3.0.0
  - freetype=2.9.1
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - matplotlib=3.0.1
  - numpy=1.15.4
  - opencv=3.4.2
  - pillow=5.3.0
  - pip=18.1
  - pyqt=5.9.2
  - python=3.6.6
  - qt=5.9.6
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.5.0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.25.2
  - tqdm=4.28.1
  - pip:
    - h5py==2.8.0
    - keras==2.2.2
    - keras-applications==1.0.4
    - keras-preprocessing==1.0.2
    - plaidbench==0.3.5
    - plaidml-keras==0.3.5
    - protobuf==3.6.1
    - pygame==1.9.4
    - tensorflow==1.12

